version: '3.4'

services:
  highway.samples.infrastructure.mongodb:
    image: mongo:latest
    container_name: highway.samples.infrastructure.mongodb    
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017    